# Generated by Django 4.0.1 on 2022-01-16 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ваше имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Ваша фамилия')),
                ('phone', models.CharField(max_length=15, verbose_name='Ваш номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша почта')),
                ('sightseeing', models.CharField(blank=True, choices=[('SC', 'Сары-Челек'), ('IK', 'Ыссык-Куль'), ('AK', 'Ала-коль'), ('AA', 'Ущелье Ала-Арча'), ('JO', 'Джети-Огуз')], max_length=100, null=True, verbose_name='Тур')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество забронированых туров')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Введите вашу почту')),
            ],
            options={
                'verbose_name': 'Присоединяйся к нам',
                'verbose_name_plural': 'Подключенные',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Область',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('reviews', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, verbose_name='Как к вам обращаться?')),
                ('user_phone', models.CharField(max_length=20, verbose_name='Ваш номер телефона')),
                ('orders', models.ManyToManyField(related_name='orders', to='tours_kg.BookNow', verbose_name='Ваши брони')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_name', models.CharField(max_length=50, verbose_name='Достопримечательность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность')),
                ('slug', models.SlugField(unique=True)),
                ('province', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='tours_kg.region', verbose_name='Место расположения')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
