# Generated by Django 4.0.1 on 2022-01-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
